export const LOG_IN = 'LOG_IN';
export const LOG_IN_BY_SOCIAL = 'LOG_IN_BY_SOCIAL';
export const LOG_IN_BY_PHONE_VERIFICATION = 'LOG_IN_BY_PHONE_VERIFICATION';
export const SIGN_UP = 'SIGN_UP';
export const LOG_OUT = 'LOG_OUT';
export const USER_INF0 = 'USER_INF0';
// export const EDIT_PROFILE = 'EDIT_PROFILE';

// news
export const GET_NEWS = 'GET_NEWS';
// export const ADD_NEWS = 'ADD_NEWS';
// export const EDIT_NEWS = 'EDIT_NEWS';

// item
export const GET_ITEM = 'GET_ITEM';
// export const ADD_ITEM = 'ADD_ITEM';
// export const EDIT_ITEM = 'EDIT_ITEM';

// junk shop
export const GET_JUNK_SHOP = 'GET_JUNK_SHOP';
export const GET_JUNK_SHOP_DETAIL = 'GET_JUNK_SHOP_DETAIL';
export const GET_ADDED_JUNK_SHOP = 'GET_ADDED_JUNK_SHOP';
export const GET_ADMIN_JUNK_SHOP = 'GET_ADMIN_JUNK_SHOP';
// export const EDIT_JUNK_SHOP = 'EDIT_JUNK_SHOP';


// contact
export const GET_CONTACT = 'GET_CONTACT';

// market place
export const GET_MARKET_PLACE = 'GET_MARKET_PLACE';
export const GET_MARKET_PLACE_DASHBOARD = 'GET_MARKET_PLACE_DASHBOARD';
export const GET_MARKET_PRODUCT_INFO = 'GET_MARKET_PRODUCT_INFO';
export const GET_MARKET_PLACE_NOTIFICATION_LIST = 'GET_MARKET_PLACE_NOTIFICATION_LIST';
export const GET_UPLOADED_MARKET_PRODUCT_LIST = 'GET_UPLOADED_MARKET_PRODUCT_LIST';
export const GET_SAVED_MARKET_PRODUCT_LIST = 'GET_SAVED_MARKET_PRODUCT_LIST';
export const GET_ORDERED_MARKET_PRODUCT_LIST = 'GET_ORDERED_MARKET_PRODUCT_LIST';
export const GET_ORDERED_ACCEPTED_MARKET_PRODUCT_LIST = 'GET_ORDERED_ACCEPTED_MARKET_PRODUCT_LIST';
export const GET_MY_MARKET_PRODUCT_ORDEDED_LIST = 'GET_MY_MARKET_PRODUCT_ORDEDED_LIST';
export const GET_MY_MARKET_PRODUCT_ORDEDED_ACCEPTED_LIST = 'GET_MY_MARKET_PRODUCT_LIST';

// wallet
export const GET_WALLET = 'GET_WALLET';
export const GET_WALLET_BY_USERID = 'GET_WALLET_BY_USERID';
